In [2]:
import pandas as pd

In [11]:
df = pd.read_csv('../../../data_synonyms/mondo_synonyms_concat.csv')
synonyms_count = df.shape[0]
node_count = df['id'].drop_duplicates().count()
print("mondo synonyms count: ", synonyms_count)
print("mondo node count: ", node_count)
print("mondo mean value: ", synonyms_count / node_count)
df.head()

mondo synonyms count:  143096
mondo node count:  29735
mondo mean value:  4.812375987893056

              id           name preferred_name
0  MONDO:0000001        disease           True
1  MONDO:0000001  other disease            NaN
2  MONDO:0000001      condition            NaN
3  MONDO:0000001      disorders            NaN
4  MONDO:0000001       diseases            NaN

In [3]:
df = pd.read_csv('../../../data_synonyms/drugbank_synonyms_concat.csv')
synonyms_count = df.shape[0]
node_count = df['id'].drop_duplicates().count()
print("drugbank synonyms count: ", synonyms_count)
print("drugbank node count: ", node_count)
print("drugbank mean value: ", synonyms_count / node_count)
df.head()

drugbank synonyms count:  342935
drugbank node count:  17430
drugbank mean value:  19.674985656913368

        id                            name preferred_name
0  DB00001                       lepirudin           True
1  DB00001                       Lepirudin           True
2  DB00001  [Leu1, Thr2]-63-desulfohirudin            NaN
3  DB00001                Desulfatohirudin            NaN
4  DB00001               Hirudin variant-1            NaN

In [13]:
df = pd.read_csv('../../../data_synonyms/go_synonyms.csv')
synonyms_count = df.shape[0]
node_count = df['id'].drop_duplicates().count()
print("go synonyms count: ", synonyms_count)
print("go node count: ", node_count)
print("go mean value: ", synonyms_count / node_count)
df.head()

go synonyms count:  177151
go node count:  48030
go mean value:  3.6883406204455547

           id                                name preferred_name
0  GO:0000001           mitochondrion inheritance           True
1  GO:0000001           mitochondrial inheritance            NaN
2  GO:0000002    mitochondrial genome maintenance           True
3  GO:0000003               obsolete reproduction           True
4  GO:0000003  reproductive physiological process            NaN

In [15]:
df = pd.read_csv('../../../data_synonyms/hpo_synonyms.csv')
synonyms_count = df.shape[0]
node_count = df['id'].drop_duplicates().count()
print("hpo synonyms count: ", synonyms_count)
print("hpo node count: ", node_count)
print("hpo mean value: ", synonyms_count / node_count)
df.head()

hpo synonyms count:  42406
hpo node count:  19650
hpo mean value:  2.1580661577608145

           id                           name preferred_name
0  HP:0000001                            All           True
1  HP:0000002     Abnormality of body height           True
2  HP:0000003   Multicystic kidney dysplasia           True
3  HP:0000003            Multicystic kidneys            NaN
4  HP:0000003  Multicystic dysplastic kidney            NaN

In [16]:
df = pd.read_csv('../../../data_synonyms/uberon_synonyms.csv')
synonyms_count = df.shape[0]
node_count = df['id'].drop_duplicates().count()
print("uberon synonyms count: ", synonyms_count)
print("uberon node count: ", node_count)
print("uberon mean value: ", synonyms_count / node_count)
df.head()

uberon synonyms count:  54283
uberon node count:  15693
uberon mean value:  3.459058178805837

               id                      name preferred_name
0  UBERON:0000000         processual entity           True
1  UBERON:0000002            uterine cervix           True
2  UBERON:0000002          cervix of uterus            NaN
3  UBERON:0000002    canalis cervicis uteri            NaN
4  UBERON:0000002  cervical canal of uterus            NaN